language: android
jdk: oraclejdk8

install: ./install_frodo2.sh

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.1
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  ./gradlew runUnitTests
